version: '3'

services:
  db:
    image: postgres
    container_name: reconator-db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: reconator-app
    environment:
      CHAT_ID: <TELEGRAM_CHAT_ID>
      API_KEY: <TELEGRAM_BOT_KEY>
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db-data:

